version: "3.9"
services:

  template:
    build: .
    image: template
    entrypoint: bash /app/start.sh
    volumes:
      - /tmp/.template/logs:/app/logs
    ports:
      - 80:5000
    networks:
      - internal
    deploy:
      restart_policy:
        condition: on-failure

networks:
  internal:
